# Generated by Django 4.2.9 on 2024-06-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
