# Generated by Django 4.2.9 on 2024-05-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_pool_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='color',
            field=models.CharField(default='rgba(0, 0, 0, 1)', max_length=50),
        ),
    ]
