# Generated by Django 4.2.9 on 2024-06-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetag',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=50),
        ),
    ]
