# Generated by Django 4.2.9 on 2024-05-31 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='tag',
            field=models.ForeignKey(choices=[('electricity', 'Electricity'), ('natural_gas', 'Natural Gas'), ('garbage', 'Garbage'), ('water', 'Water'), ('rtv', 'RTV'), ('internet', 'Internet')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensetag'),
        ),
    ]
