# Generated by Django 4.2.9 on 2024-05-31 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, choices=[('electricity', 'Electricity'), ('natural_gas', 'Natural Gas'), ('garbage', 'Garbage'), ('water', 'Water'), ('rtv', 'RTV'), ('internet', 'Internet')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expensetag'),
        ),
    ]
