# Generated by Django 4.2.9 on 2024-05-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_description_alter_expense_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
