# Generated by Django 4.2.9 on 2024-05-26 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeAllocation',
            fields=[
                ('income', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='incomes.income')),
            ],
        ),
    ]
